spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: 1qaz3edc
    url: jdbc:mysql://127.0.0.1/commons-demo?userUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
  application:
    name: commons-demo
  redis:
    host: localhost
logging:
  level:
    org.neo4j.ogm: debug