spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
  application:
    name: commons-demo
  redis:
    host: localhost
logging:
  level:
    org.neo4j.ogm: debug